export enum ROLE_CONSTANT_ENUM {
  ADMIN = 'ADMIN',
  USER = 'USER',
  GUEST = 'GUEST',
  SHIPPER = 'SHIPPER',
}

export const ROLE_CONSTANT = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  GUEST: 'GUEST',
  SHIPPER: 'SHIPPER',
};
